version: '2'
services:

  api:
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:8080"
    volumes_from:
      - api
    links:
      - api:api
